version: "3.7"
services:
  web:
    container_name: helpdesk_ict_express_lp3i_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3034:3034"
    restart: unless-stopped